# image: python:3.10

default:
  tags:
    - CI_SAST

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/integration_tests.cache/pip"

stages:
  - test
  # - deploy

before_script:
  - apt-get update 
  - apt-get install -y gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libxss1 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils
  - apt-get install -y google-chrome-stable


integration_tests:
  image: python:3.10
  stage: test
  script:
    - cd integration_tests
    - echo ENV = $TEST_ENV > .env
    - python3 --version  # For debugging
    - pip3 install virtualenv
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -e .
    - pytest -m ui --junitxml=xml_report.xml
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/integration_tests/allure-results/*
      - $CI_PROJECT_DIR/integration_tests/xml_report.xml
      # remove:
    reports:
      junit: $CI_PROJECT_DIR/integration_tests/xml_report.xml
    expire_in: 1 day

# pages:
#   image: ubuntu:latest
#   stage: deploy
#   when: always
#   script:
#     - apt-get update
#     - apt-get install ---yes allure
#     - mkdir -p public
#     - allure generate --clean  --report-dir $CI_PROJECT_DIR/integration_tests/allure-report $CI_PROJECT_DIR/integration_tests/allure-results
#     - mv $CI_PROJECT_DIR/integration_tests/allure-report/ public
#   artifacts:
#     when: always
#     paths:
#       # - public/$CI_PROJECT_DIR/integration_tests/allure-report
#       - public
#     expire_in: 1 day