
image: python:3.10

default:
  tags:
    - serhii_local_mac

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/integration_tests.cache/pip"

before_script:
  - cd integration_tests
  - python3 --version  # For debugging
  - pip3 install virtualenv
  - python3 -m venv venv
  - source venv/bin/activate
  - pip3 install -e .

test:
  script:
    - pytest -m smoke

artifacts:
  when: always


