default:
  tags:
    - CI_SAST  # docker runner

image: serhii22ua/docker-compose-python10:latest-amd64

stages:
- test

integration_backend_tests:
  services:
   - name: docker:dind
     alias: dockerhost

  variables:
    DOCKER_HOST: tcp://dockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  stage: test

  before_script:
    # up BillRun app in docker
    - cd docker/billrun-docker
    - docker compose -f docker-compose-php74.yml up -d

    # create test virtual env
    - cd $CI_PROJECT_DIR/integration_tests/
    - echo ENV = $TEST_ENV > .env
    - python3 --version  # for debugging
    - pip3 install virtualenv
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -e .

  script:
    - pytest -m smoke --junitxml=xml_report_backend.xml
    
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/integration_tests/allure-results/*
      - $CI_PROJECT_DIR/integration_tests/xml_report_backend.xml
    reports:
      junit: $CI_PROJECT_DIR/integration_tests/xml_report_backend.xml
    expire_in: 1 day
    
  only:
    - merge_requests